language: php
php:
  - 7.0
  - 7.1

before_install:
  - composer self-update

install:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - phpunit --bootstrap "vendor/autoload.php" tests
